#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV 

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^1'
bspc rule -a kitty desktop='^2'
bspc rule -a thunar desktop='^3'
bspc rule -a steam desktop='^4'
bspc rule -a spotify desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a code desktop='^7'


