#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II III
bspc monitor HDMI-0 -d IV V VI

feh --bg-fill $HOME/.local/share/backgrounds/1st.png $HOME/.local/share/backgrounds/2nd.png

$HOME/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a alacritty desktop='^2'
bspc rule -a firefox desktop='^1'
bspc rule -a discord desktop='^4'
